package com.projectdelta.jim.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val md_theme_light_primary = Color(0xFF006C4E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF7EF9C7)
val md_theme_light_onPrimaryContainer = Color(0xFF002115)
val md_theme_light_secondary = Color(0xFF1154D5)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDBE1FF)
val md_theme_light_onSecondaryContainer = Color(0xFF00174B)
val md_theme_light_tertiary = Color(0xFF6F5D00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFE16A)
val md_theme_light_onTertiaryContainer = Color(0xFF221B00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFDBE5DE)
val md_theme_light_onSurfaceVariant = Color(0xFF404944)
val md_theme_light_outline = Color(0xFF707973)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFF60DCAD)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006C4E)
val md_theme_light_outlineVariant = Color(0xFFBFC9C2)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF60DCAD)
val md_theme_dark_onPrimary = Color(0xFF003827)
val md_theme_dark_primaryContainer = Color(0xFF00513A)
val md_theme_dark_onPrimaryContainer = Color(0xFF7EF9C7)
val md_theme_dark_secondary = Color(0xFFB4C5FF)
val md_theme_dark_onSecondary = Color(0xFF002A78)
val md_theme_dark_secondaryContainer = Color(0xFF003EA8)
val md_theme_dark_onSecondaryContainer = Color(0xFFDBE1FF)
val md_theme_dark_tertiary = Color(0xFFE2C54B)
val md_theme_dark_onTertiary = Color(0xFF3A3000)
val md_theme_dark_tertiaryContainer = Color(0xFF544600)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFE16A)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF404944)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C2)
val md_theme_dark_outline = Color(0xFF89938D)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF006C4E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF60DCAD)
val md_theme_dark_outlineVariant = Color(0xFF404944)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF00A075)
val Font = Color(0xFFFFFFFF)
val light_Font = Color(0xFF006874)
val light_onFont = Color(0xFFFFFFFF)
val light_FontContainer = Color(0xFF97F0FF)
val light_onFontContainer = Color(0xFF001F24)
val dark_Font = Color(0xFF4FD8EB)
val dark_onFont = Color(0xFF00363D)
val dark_FontContainer = Color(0xFF004F58)
val dark_onFontContainer = Color(0xFF97F0FF)
